title: Codingpan's site
email: github@github.com
description: > # On the path to be a programmer.
#this means to ignore newlines until "baseurl:"
url: "/wszdwp.github.io" # the base hostname & protocol for your site
twitter_username: codingpan
github_username:  wszdwp

# Build settings
markdown: kramdown
