title: Codingpan's Blog
email: codingpan2015@gmail.com
description: > # On the path to be a programmer.
#this means to ignore newlines until "baseurl:"
url: "/wszdwp.github.io" # the base hostname & protocol for your site
twitter_username: codingpan
github_username:  wszdwp

# Build settings
# Conversion
markdown:    kramdown

excerpt_separator: ""

# how many items show per page
paginate: 12

paginate_path: "/blog/page:num/"



