title: Codingpan's Blog
email: codingpan@codingpan.com
description: > # On the path to be a programmer.
# this means to ignore newlines until "baseurl:"
# url: "/wszdwp.github.io" # the base hostname & protocol for your site
url: "/" # the base hostname & protocol for your site
github_username:  wszdwp

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge
encoding: "utf-8"

# markdown: redcarpet
# redcarpet:
#     extension:
#         - fenced_code_blocks
# highlighter: pygments

excerpt_separator: ""

# how many items show per page
paginate: 12

paginate_path: "/blog/page:num/"

# plugins
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

# Style
sass:
  sass_dir: _sass
  style: compressed


