title: Codingpan's Blog
email: wszdwp@gmail.com
description: > # On the path to be a programmer.
# this means to ignore newlines until "baseurl:"
# url: "/wszdwp.github.io" # the base hostname & protocol for your site
url: "/" # the base hostname & protocol for your site
twitter_username: codingpan
github_username:  wszdwp
linkedin_username: pan-wang-王攀-45710258
linkedin_name: Wáng Pān (王攀)

# Build settings
# Conversion
markdown: kramdown
highlighter: rouge

# markdown: redcarpet
# redcarpet:
#     extension:
#         - fenced_code_blocks
# highlighter: pygments

excerpt_separator: ""

# how many items show per page
paginate: 12

paginate_path: "/blog/page:num/"

# Gems
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

plugins:
  - jekyll-seo-tag

# Style
sass:
  sass_dir: _sass
  style: compressed


